version: "2.29.1"
services:
    db:
        image: postgres:16.4
        hostname: postgres

        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Project
            

        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
            interval: 1s
            timeout: 5s
            retries: 10
        volumes:
            - ./:/home/docker
    web:
        tty: true
        build: . 
        
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - ./:/home/docker/
    
        command: bash -c "python3 web/manage.py migrate && python3 web/manage.py runserver 0.0.0.0:8000"


