version: "2.29.1"
services:

    web_db:
        image: postgres:16.4
        container_name: web_db
        hostname: postgres
        #ports:
        #    - "5432"

        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Project
            

        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
            interval: 1s
            timeout: 5s
            retries: 10
        volumes:
            - ./:/home/docker


    web_app:
        tty: true
        container_name: web_app
        image: maximerenard/django:5.1
        ports: 
            - "8000:8000"
        depends_on:
            - web_db
        volumes:
            - ./:/home/docker/
        #
        command: bash -c "python3 web/manage.py makemigrations && python3 web/manage.py migrate && python3 web/manage.py runserver 0.0.0.0:8000"

