# Generated by Django 4.2.11 on 2024-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, default=20241909),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updateAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
