# Generated by Django 5.1.1 on 2024-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='createdat',
            field=models.IntegerField(default=20240926),
        ),
        migrations.AddField(
            model_name='product',
            name='updatedat',
            field=models.IntegerField(default=20240926),
        ),
    ]
