# Generated by Django 5.1.1 on 2024-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_createdat_product_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdat',
            field=models.IntegerField(default=20240926),
        ),
        migrations.AlterField(
            model_name='product',
            name='updatedat',
            field=models.IntegerField(default=20240926),
        ),
    ]
