# Generated by Django 5.1.1 on 2024-09-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_product_createdat_alter_product_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('High-Tech', 'High Tech'), ('Suits', 'Suits'), ('Program', 'Program'), ('PC_Component', 'Pc Component'), ('Accessories', 'Accessory'), ('Others', 'Others')], default='Others', max_length=13),
        ),
    ]
