# Generated by Django 4.2.11 on 2024-09-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_alter_product_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="createdAt",
            field=models.DateTimeField(default="2024-09-19 16:48:31.914023"),
        ),
    ]
