# Generated by Django 4.2.11 on 2024-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_alter_product_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
